swagger: '2.0'
info:
  version: 1.0.0
  title: praveen_api
  x-ibm-name: praveen_api
basePath: /praveen_api
x-ibm-configuration:
  properties:
    target-url:
      value: https://www.google.com
      description: URL of the proxy policy
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - invoke:
          title: invoke
          version: 2.0.0
          verb: keep
          target-url: $(target-url)
          follow-redirects: false
          timeout: 60
          parameter-control:
            type: allowlist
            values: []
          header-control:
            type: blocklist
            values: []
          inject-proxy-headers: true
paths:
  /:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  praveen_scheme:
    type: oauth2
    x-ibm-oauth-provider: praveen_oauth
    flow: application
    tokenUrl: https://$(catalog.url)/praveen_oauth/oauth2/token
    scopes:
      sample_scope_1: Sample scope description 1
  untitled:
    type: oauth2
    x-ibm-oauth-provider: vamsi
    flow: application
    tokenUrl: https://$(catalog.url)/vamsi/oauth2/token
    scopes:
      vamsi: Sample scope description 1
  p_impli:
    type: oauth2
    x-ibm-oauth-provider: praveen_oauth
    flow: implicit
    authorizationUrl: https://$(catalog.url)/praveen_oauth/oauth2/authorize
    scopes:
      sample_scope_1: Sample scope description 1
security:
  - clientID: []
  - praveen_scheme:
      - sample_scope_1
  - untitled:
      - vamsi
  - p_impli:
      - sample_scope_1
schemes:
  - https
