info:
  version: 1.0.0
  title: Product_s
  name: product_s
gateways:
  - datapower-api-gateway
plans:
  default-plan:
    title: Default Plan
    description: Default Plan
    rate-limits:
      default:
        value: 100/1hour
    apis:
      hospital_reservevation1.0.0: {}
apis:
  hospital_reservevation1.0.0:
    $ref: hospital_reservevation_1.0.0.yaml
visibility:
  view:
    type: public
    orgs: []
    tags: []
    enabled: true
  subscribe:
    type: authenticated
    orgs: []
    tags: []
    enabled: true
product: 1.0.0
